### ISSUE TITLE
CVAE example errors

### ISSUE THREAD

**Issue by juandspy** [ml5js/ml5-examples#260]
Dear ml5 community, 

I found some errors in CVAE example, by @WenheLI and @Derek-Wds .

When I try to run [CVAE_QuickDraw](https://editor.p5js.org/ml5/sketches/CVAE_QuickDraw) on Firefox it logs this error:

```
modelReady@about:srcdoc:46:21
e.default/</e[n]/<@https://unpkg.com/ml5@0.4.3/dist/ml5.min.js:124:28684
e.default/<@https://unpkg.com/ml5@0.4.3/dist/ml5.min.js:56:26142
```

On the other hand, running it on Chrome returns this error:

```
TypeError: cvae.labels is not iterable
    at modelReady (about:srcdoc:46:26)

    at https://unpkg.com/ml5@0.4.3/dist/ml5.min.js:124:28684

    at https://unpkg.com/ml5@0.4.3/dist/ml5.min.js:56:26141
```

**Comment by WenheLI** [comment]
Thanks, @juandspy ! 
I have inspected this example quickly. It seems that the `manifest` file is not loaded in this project.
I think it is a problem with the p5editor? cc @joeyklee 
Have you tried if this works locally?

**Comment by juandspy** [comment]
I didn't, sorry. I was just having a look at the project.
